#--------------------Stage 1--------------------#
#---------------------This was not working
FROM python:3.9 AS backend-builder
WORKDIR /app

COPY backend/ /app
RUN pip install --no-cache-dir -r requirements.txt

#-----------------Stage2----------------------#
FROM python:3.9-slim-buster
WORKDIR /app
COPY --from=backend-builder /app /app
EXPOSE 5000
ENV NAME World
CMD ["python", "-m", "venv", "venv"]
CMD ["/bin/bash", "-c", "source venv/bin/activate && python app.py"]
# CMD ["python","app.py"]
